name: protect main from direct updates
on:
  push:
    branches: [ mainó ]
jobs:
  job-id:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update branch protection
        uses: Hatzelencio/branch-protection@v0.0.0
        env:
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}